package main;

public class Main
{
	static public String[] characterIdeas;
	public static void main(String[] args)
	{
		GUI.createGUI();
		
		characterIdeas = new String[15];

		characterIdeas[0] = "MACHIAVELLIAN GNOME DRUID FROM A HIGH-CLASS BROTHEL WHO LOVES TO HAGGLE";
		characterIdeas[1] = "LOUD HALFLING BARBARIAN FROM A CLIFF-SIDE VILLAGE WHO IS SEARCHING FOR THE KNOWLEDGE OF TRUE IMMORTALITY";
		characterIdeas[2] = "POMPOUS ELF ROGUE FROM A TOURIST TOWN IN THE MOUNTAINS WHO LIKES TO SETTLE ARGUMENTS WITH AN ARM WRESTLE";
		characterIdeas[3] = "COMPASSIONATE HUMAN DRUID FROM A SILK & SPICES TRADE GALLEY WHO BELIEVES DUNGEON CRAWLING IS JUST BREAKING AND ENTERING";
		characterIdeas[4] = "DEPENDABLE HUMAN FIGHTER FROM THE MEAN UNCOBBLED STREETS OF THE CITY WHO BELIEVES THEY HAVE A CLAIM TO THE THRONE";
		characterIdeas[5] = "UNBALANCED DRAGONBORN WIZARD FROM A FALLEN KINGDOM WHO HASN'T ACCOMPLISHED ANYTHING IN THEIR SHORT LIFE YET";
		characterIdeas[6] = "CRASS HALF-ELF CLERIC FROM A FALLEN KINGDOM WHO CONSTANTLY PLACES THEMSELVES IN DANGER, JUST TO PROVE A POINT";
		characterIdeas[7] = "FRIENDLY GNOME ROGUE FROM A DESTITUTE PLANTATION WHO WAS RAISED AS A HOSTAGE BY THEIR FATHER'S ENEMIES";
		characterIdeas[8] = "GRAVE HALF-ELF BARD FROM A LOW CEILINGED CASTLE WHO HATES RIDING HORSES";
		characterIdeas[9] = "PROUD ELF WARLOCK FROM THE ICEBERG SEA WHO SEEMS TO KNOW EVERYONE";
		characterIdeas[10] = "ENTERPRISING ELF BARD FROM THE IMPROBABLE PEAKS WHO ALWAYS KEEPS THEIR PROMISES";
		characterIdeas[11] = "RESOURCEFUL HUMAN CLERIC FROM THE SLUMS OF A PORT CITY WHO NO LONGER DREAMS";
		characterIdeas[12] = "COURAGEOUS HALF-ORC BARD FROM A PRISON COLONY WHO HAS NEVER BEEN KISSED";
		characterIdeas[13] = "RESENTFUL HALFLING WARLOCK FROM THE BASE OF A VOLCANO WHO KNOWS SEVEN DANGEROUS SECRETS";
		characterIdeas[14] = "HOT-HEADED HALF-ELF ROGUE FROM THE WET DESERT WHO WANTS TO BE FAMOUS, NO MATTER WHAT";
	}
}
